### PR TITLE
Created compendiums for Cyberware

### PR DESCRIPTION
**Pull request by cybersmily**
Added the compendiums for cyberware.db and chipware.db. 
Add more props to Cyberware for type, subtypes, slots, spaces, abbrev as well as added to the templates.
- Type - this property is to hold the item cateogry like Bioware, Neuralware, Implant, Cyberlimb, etc.
- Subtype - field to trap if the cyber is an option mostly. This will help with adding options to cyber that have them, like Cyberoptics.
- Slots - The limiting number of options for cyberware, ex optics has 4 per eye. Field is set to 0 if it doesn't have options or there is an unlimited amount of options.
- Spaces - If it is an option subtype, how many slots will it use. Default 1 if it is an option. For non-options field is set to 0.
- Abbrev - in the main book Cyberware had abbreviations so included it as well

Add source property to items template to capture the source of the item.

### CODE REVIEW

**Comment by drowzero0** [comment]
i was checking the core-rulebook for the creation of my misc db and found some surgeries that seem to be Bodysculptings but without any HL.
for example this one, found in the core-rulebook on page 121 - section trauma team:
image
 are those already in your DB? i was not able to find them on your site.

**Comment by OctarineSourcerer** [comment]
Just going through this now. Good so far! Just adding a migration path for items without source, and putting the source display box in the settings so anyone doing homebrew doesn't always have to have a blank box saying "Source" there, and people get a little more room for flavour, though to be honest I'm not sure they need it. That change is open to debate though, if you think that's a bad change :) Here's a screenshot!

image

**Comment by cybersmily** [comment]
I thought I put source right below Flavor box. Maybe that's in my second push I did, waiting on the merge to happen

**Comment by OctarineSourcerer** [comment]
No, you're right, that was one of the changes I made. I also changed a bit of text in the cyberware tab to make things a little more clear, and if cyberware didn't have a category I made it not display `()` on its listing

**Pull request merged**
