### PR TITLE
Develop - added the new Rifle DB 

### PR DESCRIPTION
**Pull request by drowzero0**
i am not used to work with git and i am not a developer (but i know how to read code) so i tried to add the rifle db and added an entry into the system.json.
if there is more to be done, then ignore it, or let me know what to do, if i can make your life easier that way =)
the last changes i saw where mainly those to steps for the pistols.db

### CODE REVIEW

**Comment by cybersmily** [comment]
Hey drowsero0, like you trying to figure out how to code for foundry. One thing I saw in the db was source being Cyberpunk2021. Is that from a site or suppose to be CP2020 from RTG? Also, source is important if you are following the Homebrew rules. Keep that in mind. 
One thing I am still trying to understand (granted it has only be a few days since I started with Foundry) and maybe something OctarineSourcerer can chime in on, is that the equipement db will contains all equipement, guns, cyber, gear. Or at least that is what I'm seeing when I looked at a couple of other systems in git. I could be wrong, but it seems that way as they are all derived from the item template. 
Lastly, kudos for manually importing all that data. One thing I hate is data entry hehe :)

**Comment by cybersmily** [comment]
on the point of db thing, I was ignorant on how it works. XD Now that I created a cyberware db and getting it added, now I understand how it works.

**Comment by drowzero0** [comment]
as mentioned in this issue https://github.com/OctarineSourcerer/cyberpunk2020/issues/55 i am using http://cyberpunk.asia/ for my weapon references. its a collection of a lot weapons. i just used the sources that he tagged with each weapon.
if thats wrong, i can correct it and create the new corrected db file, i just need to know what to change =)

for the db thing am just using diffrent db files for each weapontype just to make the compendium easier to search by type.
when i am done, i will also create a whole weapons.db as a compendium, which than can be used as items in foundry.
as far as i realized, if you "import" a compendium, its stored data from ~/foundrydata/Data/worlds/cyberpunk_2020/packs$
image
gets written into those diffrent db files in  ~/foundrydata/Data/worlds/cyberpunk_2020/data$
with the following .db files:
image

(screens are from my current play-world and can contain more .db files for diffrent used modules)

**Comment by OctarineSourcerer** [comment]
It's pretty much as drowsero0 says for having different dbs for different item types - under the hood, they'd all just be `Item` (just with different `type` and therefore `data` each), so could technically be in one compendium. But that compendium would be _really_ big, and it just makes sense to at least split them up for the sake of letting players more easily navigate them. 

And yes, about the "importing" a compendium into a world drowsero0, I think its items do get written to the `worlds/{worldName}/data` dbs, as far as I understand it. Though, take that with a pinch of salt, I've not checked!
One thing to keep in mind is that all entities _in the world_, that is, not just stored in compendiums, will be sent to/loaded by the other players, so one way to decrease loadtime is to only have items you need at the moment in the world itself, and everything else in compendiums.

I'll have a peek at this later drowsero0 (in an RPG break as I write this), but good work! It's appreciated :) I might have to run a migrate on the compendium pack, depending on the version it was made with, but that's no issue at all as I've pretty much written the method to do that for weapons especially already.

I may at some point take @cybersmily up on the offer of the jsons used on his site - actually, if you send those over to me, I could see about generating compendium files from them. Would probably speed up the rest of items :)

**Comment by cybersmily** [comment]
actually created a cyberware.db using a converter script I found online for yaml files. Just needed to tweak it our purposes. Experimenting right now how compedium work and how to create subfolders in a compedium, so that if you import Cyberware, it breaks them out into different subfolders. Have a feeling that it won't be possible. If that's the case I will look into creating multiple db for each type (optics, implants, neuralware, etc.)

**Comment by OctarineSourcerer** [comment]
> actually created a cyberware.db using a converter script I found online for yaml files. Just needed to tweak it our purposes. Experimenting right now how compedium work and how to create subfolders in a compedium, so that if you import Cyberware, it breaks them out into different subfolders. Have a feeling that it won't be possible. If that's the case I will look into creating multiple db for each type (optics, implants, neuralware, etc.)

It's actually fairly possible I think! The 13th age system does it 
image
https://gitlab.com/asacolips-projects/foundry-mods/archmage

I've yet to check out the docs for this, and won't get to put in any real time until tomorrow if at all this week, but there's at least encouragement that it can be done, though I don't know if it would import them into separate folders.

Even if not though, different DBs is perfectly fine imo.

**Comment by drowzero0** [comment]
i am not sure how you are using subfolders, but for folders i am using the extra foundry module: 
https://foundryvtt.com/packages/compendium-folders
this works great but in my case the compendiums load like 10s till the folderstructure is shown. thats why i decided to create single compendium.db files. for each type. load is much faster that way.

for importing i am using a module that imports csv files into a compendium.
so i am creating massive lists, import them into the world with this module:
https://foundryvtt.com/packages/data-toolbox

**Comment by OctarineSourcerer** [comment]
Okay, so the rifles should be added now. Couple tweaks needed (missing comma in system.json and migration needed to add damageRanges to weapons in there) but all good.

**Pull request merged**
